export enum ActionsType {
    FIRE = 'FIRE',
    COLLISION = 'COLLISION',
    EXERCISES = 'EXERCISES',
    LOCAL_RISK = 'LOCAL_RISK',
    SEARCH_RESCUE = 'SEARCH_RESCUE',
    SECURITY = 'SECURITY',
    ACCIDENT = 'ACCIDENT',
    FALSE_ALARMS = 'FALSE_ALARMS'
}
