export enum CourseKind {
  BASIC = 'BASIC',
  TECHNICAL_RESCUE = 'TECHNICAL_RESCUE',
  FIRST_AID = 'FIRST_AID',
  WATER_RESCUE = 'WATER_RESCUE',
  HARDWARE_CONSERVATOR = 'HARDWARE_CONSERVATOR',
  CHEMICAL_AND_ECOLOGICAL_RESCUE = 'CHEMICAL_AND_ECOLOGICAL_RESCUE',
  ALTITUDE_RESCUE = 'ALTITUDE_RESCUE',
  SERVICE_CAR_WITH_LIFT = 'SERVICE_CAR_WITH_LIFT',
  SERVICE_CAR_WITH_LADY = 'SERVICE_CAR_WITH_LADY',
  SEARCH_AND_RESCUE = 'SEARCH_AND_RESCUE',
  COMMANDERS = 'COMMANDERS',
  WARDROBES = 'WARDROBES',
  COMMUNES_COMMANDER = 'COMMUNES_COMMANDER'
}
