export enum SpecialCarsPurpose {
  LADDER = 'LADDER',
  HYDRAULIC_JACK = 'HYDRAULIC_JACK',
  ROAD_RESCUE = 'ROAD_RESCUE',
  TECHNICAL_RESCUE = 'TECHNICAL_RESCUE',
  CHEMICAL_RESCUE = 'CHEMICAL_RESCUE',
  ENVIRONMENTAL_RESCUE = 'ENVIRONMENTAL_RESCUE',
  WATER_RESCUE = 'WATER_RESCUE',
  LIFESAVING = 'LIFESAVING',
  CRANE = 'CRANE',
  OPERATING = 'OPERATING',
  COMMAND_AND_COMMUNICATION = 'COMMAND_AND_COMMUNICATION',
  SERPENTINE = 'SERPENTINE',
  MEDICAL = 'MEDICAL',
  AN_ANTI = 'AN_ANTI',
  QUARTERMASTER = 'QUARTERMASTER'
}
